kind: Service
apiVersion: v1
metadata:
  name: nodejs-be
  labels:
    app: nginx-nodejs-app
spec:
  selector:
    app: nginx-nodejs-app
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-be
  labels:
    app: nginx-nodejs-app
spec:
  selector:
    matchLabels:
      app: nginx-nodejs-app
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-nodejs-app
        tier: backend
        track: stable
    spec:
      containers:
      - name: nodejs-be
        image: "apps_nodejs-be"
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 4000