kind: Service
apiVersion: v1
metadata:
  name: splunk-forwarder
  labels:
    app: splunk-forwarder-app
    tier: splunk
spec:
  selector:
    app: splunk-forwarder-app
  ports:
  - name: to-indexer
    port: 9997
    targetPort: 9997
    protocol: TCP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: splunk-forwarder
  labels:
    app: splunk-forwarder-app
    tier: splunk
spec:
  selector:
    matchLabels:
      app: splunk-forwarder-app
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: splunk-forwarder-app
        tier: splunk
        track: stable
    spec:

      volumes:
      - name: configmap-forwarder
        configMap:
          name: splunk-forwarder-config

      # If testing the splunk tier as standalone - comment this
      - name: syslog-logs
        persistentVolumeClaim:
          claimName: 'logs-claim'

      #hostAliases:
      #- ip: "192.168.99.108" #Might be replaced by a relevant vagrant machine IP
      #  hostnames:
      #  - "splunk-indexer"

      containers:
      - name: splunk-forwarder
        image: splunk/splunk:latest
        imagePullPolicy : Always
        env:
        - name: SPLUNK_START_ARGS
          value: --accept-license --answer-yes

        - name: SPLUNK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: splunk-secret
              key: password

        volumeMounts:
        - name: configmap-forwarder
          mountPath: /tmp/defaults/default.yml
          subPath: "default.yml"

        # If testing the splunk tier as standalone - comment this
        - name: syslog-logs
          mountPath: /opt/splunk/var/log/syslog-logs

