apiVersion: v1
data:
  syslog-ng.conf: |-
    @version: 3.5
    @include "scl.conf"
    #@include "`scl-root`/system/tty10.conf"

    options {
         time-reap(30);
         mark-freq(10);
         keep-hostname(yes);
    };

    source s_local {
            system();
            internal();
    };

    destination d_remote {
           network("syslog-collector" transport(udp) port(514));
           network("syslog-collector" transport(tcp) port(514));
    };

    log { source(s_local);destination(d_remote); };
kind: ConfigMap
metadata:
  creationTimestamp: "2019-08-19T20:08:21Z"
  name: syslog-client-config
  namespace: logs-ns
  resourceVersion: "74775"
  selfLink: /api/v1/namespaces/logs-ns/configmaps/syslog-client-config
  uid: ad475bab-e34c-4747-87da-a96a7d755186
