kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: logs-claim
    labels:
      app: logs-app
      tier: logs
spec:
    accessModes:
      - ReadWriteMany
    #storageClassName: logs-volume
    resources:
        requests:
            storage: 1Gi