apiVersion: v1
data:
  syslog-ng.conf: |2-

    @version: 3.5
    @include "scl.conf"
    #@include "`scl-root`/system/tty10.conf"

    options {
         time-reap(30);
         mark-freq(10);
         keep-hostname(yes);
    };

    source s_local { system(); internal(); };
    source s_network {
         syslog(transport(udp) port(514));
         syslog(transport(tcp) port(514));
    };

    destination d_local {
       file(
             "/var/log/syslog-ng/logs.txt"
             owner("root")
             group("root")
             perm(0777)
        );
    };

    destination d_remote {
      file("/var/log/syslog-ng/logs_${HOST}");
    };

    log { source(s_local); destination(d_local); };
    log { source(s_network); destination(d_remote); };
kind: ConfigMap
metadata:
  creationTimestamp: "2019-08-19T20:08:21Z"
  name: syslog-collector-config
  namespace: logs-ns
  resourceVersion: "74776"
  selfLink: /api/v1/namespaces/logs-ns/configmaps/syslog-collector-config
  uid: 305bc529-b537-4a57-b9e3-f1723109883b
